"""Report formatter for atl-context-scout.

Takes structured data from the Brave client and Notion vault and
renders a clean, human-readable markdown context report to stdout.
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from typing import Any


def _section(title: str, items: list[dict[str, str]], max_items: int = 5) -> str:
    """Render a named section with a list of result items."""
    lines = [f"## {title}", ""]
    for item in items[:max_items]:
        headline = item.get("title", "").strip()
        description = item.get("description", "").strip()
        url = item.get("url", "").strip()
        if headline:
            lines.append(f"**{headline}**")
        if description:
            # Wrap long descriptions at 90 chars
            wrapped = textwrap.fill(description, width=90, subsequent_indent="  ")
            lines.append(wrapped)
        if url:
            lines.append(f"  {url}")
        lines.append("")
    return "\n".join(lines)


def build_report(
    location: str,
    news: list[dict[str, str]],
    weather: list[dict[str, str]],
    events: list[dict[str, str]],
    phone: str = "",
) -> str:
    """Compose the full markdown report string."""
    timestamp = datetime.now().strftime("%A, %B %-d, %Y %-I:%M %p")
    header_lines = [
        f"# ATL Context Scout — {location}",
        f"_Generated {timestamp}_",
        "",
    ]
    if phone:
        header_lines += [
            f"_Personalized report for: +1 {phone}_",
            "",
        ]

    header_lines += [
        "---",
        "",
    ]

    sections = [
        _section("Latest News", news),
        _section("Weather", weather, max_items=3),
        _section("Events & Things To Do", events),
    ]

    footer = [
        "---",
        "_Data sourced from Brave Search. Report generated by atl-context-scout._",
    ]

    return "\n".join(header_lines + sections + footer)
